/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AccessAlarmOutlined: typeof import('@vicons/material')['AccessAlarmOutlined']
    ApertureSharp: typeof import('@vicons/ionicons5')['ApertureSharp']
    NButton: typeof import('naive-ui')['NButton']
    NIcon: typeof import('naive-ui')['NIcon']
  }
}
